
# date when accessing KEGG FTP
date_suffix: 2026-04-08

# list of target organisms' ID
species_id:
  - Sbi
  - Ghi
  - Bna
  - Cre
  - Sot
  - Osi
  - Cit
  - Bdi
  - Nta
  - Ath
  - Bra
  - Gma
  - Mtr
  - Osa
  - Ppo
  - Sly
  - Vvi
  - Zma
  - Tae
  - Hvu

taxonomy_id:
  - 4558
  - 3635
  - 3708
  - 3055
  - 4113
  - 39946
  - 2711
  - 15368
  - 4097
  - 3702
  - 3711
  - 3847
  - 3880
  - 39947
  - 3694
  - 4081
  - 29760
  - 4577
  - 4565
  - 4513

genes_ko_list_download: https://ftp.kegg.net/kegg/genes/links/genes_ko.list.gz
genes_pathway_list_download: https://ftp.kegg.net/kegg/genes/links/genes_pathway.list.gz
genes_id_download: https://ftp.kegg.net/kegg/genes/links/genes_ncbi-geneid.list.gz